[workspace]
members = ["shared", "notification_provider"]

[package]
name = "autopower"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"
incremental = true

[dependencies]
autopower_shared = { path = "shared" }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
windows = { version = "0.48", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Environment",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Registry",
    "Win32_System_Power",
    "Win32_System_Services",
    "Win32_System_Threading",
    "Win32_System_SystemServices",
    "Win32_System_RemoteDesktop",
    "Win32_System_Pipes",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_Diagnostics_Debug",
] }
